### ISSUE TITLE
[enhancement ]: Show usage of !important rule

### ISSUE THREAD

**Issue by nuno-andrade-ui** [bartveneman/wallace-cli#73]
I believe showing the usage of the `!important` will be a nice-to-have in the output. 
As on the stats of the CSS you already have that information I believe it is 'declarations.importants.total', it will be just a matter of showing that info on the output. 

I am just not sure exactly where to put it, but as you already have empty rules, font-faces, etc ... maybe it could stay also inside the performance section, how do you feel about it?

**Comment by bartveneman** [comment]
Yes, good idea! I must have forgotten to implement it initially.
