### ISSUE TITLE
Incorrect CSS authoring can cause cli to fail

### ISSUE THREAD

**Issue by clanceyp** [bartveneman/wallace-cli#78]
`@media (min-width: 1000px) { ... }` missing semi colon here causes the CSS parser to fail. e.g. `$ wallace https://www.gatsbyjs.org`

**Comment by bartveneman** [comment]
```bash
SyntaxError: Missed semicolon at line 220, column 539:

  218 | }.css-mj31jj { -webkit-box-align: center; align-items: center; display: flex; z-index: 1; }.css-mj31jj span { color: var(--theme-ui-colors-link-color,#8a4baf); border-bottom: 1px solid var(--theme-ui-colors-link-border,#d9bae8); }a.css-mj31jj { font-weight: normal; }@media (min-width: 1000px) {
  219 |   .css-mj31jj:hover span { border-color: var(--theme-ui-colors-link-hoverBorder,#8a4baf); }
> 220 | }.css-csk973 { border-radius: 100%; display: inline-block; margin: 0rem 0.75rem 0rem 0rem; transform: translateZ(0px); vertical-align: top; }.css-1lxugp9 { align-items: flex-end; background: transparent; bottom: 0px; color: var(--theme-ui-colors-card-color,#78757a); display: flex; -webkit-box-flex: 1; flex-grow: 1; font-size: 0.875rem; left: 0px; padding: 1.25rem; position: absolute; right: 0px; top: 0px; z-index: 0; }.css-1lxugp9:hover { background: yellow; }.css-1lxugp9 svg { height: 1rem; width: 1rem; }.css-1lxugp9 span { color: color:var(--theme-ui-colors-link-color,#8a4baf); border-top-color: ; border-top-style: ; border-top-width: ; border-right-color: ; border-right-style: ; border-right-width: ; border-left-color: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-bottom: 1px solid var(--theme-ui-colors-link-border,#d9bae8); font-weight: bold; margin-right: 0.25rem; }@media (min-width: 1000px) {
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ^
  221 |   .css-1lxugp9 { padding: 2rem; }
  222 |   .css-1lxugp9 span:hover { border-color: var(--theme-ui-colors-link-hoverBorder,#8a4baf); }
```

There seems to be an actual CSS syntax error, so the analyzer doesn't know how to transform the CSS into something to analyze. Did you get this exact error too?

**Comment by bartveneman** [comment]
@clanceyp can you confirm that you got this same error message too?

**Comment by clanceyp** [comment]
Ah yes,. you're right the CSS is broken. I'll close this ticket

**Comment by eloyesp** [comment]
Hello, I'm just facing the same error, but I would really want a way to workaround this, because, I do not control all the css files (so I cannot fix the issue) and the error does not even mention the actual file causing the issue.

So, it would be awesome to have the error mention the broken file (no only line number):

    SyntaxError: Missed semicolon at file.css on line 220, column 539:

Also it would be nice to have an option to skip those (as browsers do):

    $ wallace --skip-broken https://www.gatsbyjs.org
    WARNING: skipping broken file: gatsbyjs.org/file.css
    [RESULTS...]
    
Regards.

**Comment by bartveneman** [comment]
@eloyesp This is because the css-analyzer is several major versions behind. Newer versions are very resilient to invalid CSS. I'm planning to release a new version of wallace-cli that has this latest version. Work already started in a v3 branch in this repo [branch](https://github.com/projectwallace/wallace-cli/tree/v3)
