### ISSUE TITLE
Using it with authenticated pages

### ISSUE THREAD

**Issue by raziel8** [bartveneman/wallace-cli#87]
How is it possible to use it with authenticated pages?

**Comment by bartveneman** [comment]
That is not a feature Wallace-CLI currently supports. What are you specifically trying to do?

**Comment by bartveneman** [comment]
I'm happy to accept a PR for this. Perhaps authentication via an HTTP could work.

**Comment by bartveneman** [comment]
Leaving this link here, because I think it is a good explainer why Wallace should not be supporting this feature: https://github.com/cssstats/cssstats/issues/296#issuecomment-753430238
